### PR TITLE
Py3 port, 1st step : command.py example working

### PR DESCRIPTION
**Pull request by ckolumbus**
refactored the whole string based communication using bytes/bytearrays now + some minor stuff 
todo: EventManager handling not working yet, debugging ongoing.

### CODE REVIEW

**Comment by braingram** [comment]
Awesome! I started a branch 'py3' where I'm using what you've added and trying to make things both py2 and py3 compatible. So far it works in both version (2.7.6 and 3.4.3) to blink an led and passes the test_type_conversion.

I'm realizing I'm missing some test cases, so will work on filling those in. Thanks again!

**Comment by braingram** [comment]
I made some more changes and updated a few tests and examples. So far I'm seeing everything run fine in python 2.7.6 and 3.4.3. What I've tried is:
example/commands.py
example/events.py
example/namespace.py  [new]
tests/01_simple
tests/02_protocol
tests/text_protocol
tests/send_receive [this one's probably the most thorough]

Let me know if you have a chance to test it out and if you run into any issues.

**Comment by ckolumbus** [comment]
**UPDATE:**  I read the tests and found the comment with the sleep after init the serial line. I added  the "timer.sleep(1)" after all serial init lines and now everything works!

I keep the post below for reference, but the sleep fixed it all.

------ 

Sorry, didn't get much time to test lately.
I still get some weird behaviour. commando.py does work, neither events.py nor namespace.py works. It always gets stuck on the first "blocking_trigger"  call, which never returns.
I'm running Manjaro Linux (based on ArchLinux) and I tried arduino dev ide v.1.8.0 as well as command line based builds with [Arduino-Makefile](https://github.com/sudar/Arduino-Makefile) with manjaro avr build package based on arduino 1.6.17. No success.

I didn't have too much time to investigate so I can give you only some information right now. I ran the test suite an the output of send_receive (send_messages.py with send_message.ino loaded) looks like this:

Python 3.6.0:
```       <- from computer, -> = from arduino
[text]<-'hi'
[text]<-'how are you'


[cmd]<- 0 [None]

[cmd]<- 1 [[True, False]]

[cmd]<- 2 [[c_char(b'\r'), c_char(b'\n'), c_char(b'a'), c_char(b'Z'), c_char(b'\x00')]]

[cmd]<- 3 [[0, 1, -1, 1000000, -1000000]]

[cmd]<- 4 [[0.0, 1.0, -1.0, 1.23, -123.0]]

[cmd]<- 5 [['hi', 'hello', '']]
```

with Python 2.7 13:
```        <- from computer, -> = from arduino

[text]<-'hi'

[text]<-'how are you'
()
()
[cmd]<- 0 [None]
()
[cmd]<- 1 [[True, False]]
()
[cmd]<- 2 [[c_char('\r'), c_char('\n'), c_char('a'), c_char('Z'), c_char('\x00')]]
()
[cmd]<- 3 [[0, 1, -1, 1000000, -1000000]]
()
[cmd]<- 4 [[0.0, 1.0, -1.0, 1.23, -123.0]]
()
[cmd]<- 5 [['hi', 'hello', '']]```

Doesn't really look good, but as said, I did not look into this deeper yet.

Do you have any Idea what's going on?

**Comment by braingram** [comment]
It sounds like things are working now?

Is this being run on an Arduino Uno? Any clue why it needs the sleep? My suspicion is that the reset-on-connect triggers the bootloader to wait for some period of time.

I hope things are working for you know :)

**Comment by ckolumbus** [comment]
Yes, all my tests are successful. I have an mega2560 hooked up on USB. The sleep seems to be necessary. I do also have an uno from SaintSmart. Gonna try this also to see how it behaves.
So currently I'm fine! Thanks for your support! I'll let you know how the projects actually develops 😃

**Pull request closed without merging**
